package io.kaszabimre.skymate.util

@Suppress("MagicNumber", "LongMethod", "CyclomaticComplexMethod")
fun getWeatherCondition(code: Int): String = when (code) {
    0 -> "Clear sky"
    1 -> "Mainly clear"
    2 -> "Partly cloudy"
    3 -> "Overcast"
    4 -> "Fog or thick haze"

    5 -> "Haze"
    6 -> "Widespread dust"
    7 -> "Dust or sand raised by wind"
    8 -> "Well-developed dust or sand whirls"
    9 -> "Duststorm or sandstorm"

    10 -> "Mist"
    11 -> "Patches of shallow fog"
    12 -> "Continuous shallow fog"
    13 -> "Lightning visible, no thunder"
    14 -> "Precipitation within sight, not reaching ground"
    15 -> "Precipitation within sight, reaching ground"
    16 -> "Virga"
    17 -> "Thunderstorm, no precipitation"
    18 -> "Squalls"
    19 -> "Funnel cloud(s)"

    20 -> "Drizzle or rain not reaching ground"
    21 -> "Rain showers"
    22 -> "Snow showers"
    23 -> "Mixed rain and snow"
    24 -> "Freezing drizzle or freezing rain"
    25 -> "Drizzle, freezing, or sleet"
    26 -> "Rain, freezing"
    27 -> "Snow, heavy"
    28 -> "Snow, moderate"
    29 -> "Snow, light"

    30 -> "Slight duststorm or sandstorm"
    31 -> "Moderate duststorm or sandstorm"
    32 -> "Severe duststorm or sandstorm"
    33 -> "Blowing snow, slight"
    34 -> "Blowing snow, moderate"
    35 -> "Blowing snow, severe"
    36 -> "Thunderstorm in vicinity"
    37 -> "Rain showers in vicinity"
    38 -> "Snow showers in vicinity"
    39 -> "Thunderstorm with rain/snow in vicinity"

    40 -> "Fog in patches"
    41 -> "Fog, sky visible"
    42 -> "Fog, sky obscured"
    43 -> "Fog, thinning"
    44 -> "Fog, thickening"
    45 -> "Fog"
    46 -> "Fog with haze"
    47 -> "Fog, lifting"
    48 -> "Depositing rime fog"
    49 -> "Freezing fog"

    50 -> "Slight drizzle"
    51 -> "Moderate drizzle"
    52 -> "Heavy drizzle"
    53 -> "Slight freezing drizzle"
    54 -> "Moderate freezing drizzle"
    55 -> "Heavy freezing drizzle"
    56 -> "Slight freezing rain"
    57 -> "Moderate freezing rain"
    58 -> "Heavy freezing rain"
    59 -> "Freezing rain, severe"

    60 -> "Slight rain"
    61 -> "Moderate rain"
    62 -> "Heavy rain"
    63 -> "Very heavy rain"
    64 -> "Extreme rain"
    65 -> "Torrential rain"
    66 -> "Light freezing rain"
    67 -> "Heavy freezing rain"
    68 -> "Freezing rain and snow"
    69 -> "Freezing precipitation, unspecified"

    70 -> "Light snow fall"
    71 -> "Moderate snow fall"
    72 -> "Heavy snow fall"
    73 -> "Snow with wind"
    74 -> "Snowstorm"
    75 -> "Snowstorm, heavy"
    76 -> "Ice pellets"
    77 -> "Snow grains"
    78 -> "Isolated snowflakes"
    79 -> "Ice needles"

    80 -> "Slight rain showers"
    81 -> "Moderate rain showers"
    82 -> "Violent rain showers"
    83 -> "Showers of rain and snow"
    84 -> "Snow and rain showers, heavy"
    85 -> "Slight snow showers"
    86 -> "Heavy snow showers"
    87 -> "Snow squalls"
    88 -> "Blizzard conditions"
    89 -> "Blowing snow"

    90 -> "Thunderstorm without precipitation"
    91 -> "Thunderstorm with light rain"
    92 -> "Thunderstorm with heavy rain"
    93 -> "Thunderstorm with snow"
    94 -> "Thunderstorm with sleet"
    95 -> "Thunderstorm"
    96 -> "Thunderstorm with slight hail"
    97 -> "Thunderstorm with heavy hail"
    98 -> "Tornado, waterspout"
    99 -> "Severe thunderstorm with tornado"

    else -> "Unknown weather condition"
}
